Repository kubernetes-sigs/k8s-gsm-tools, pull requests merged in 2020-07, with the labels that each got.

#1 In cluster controller
  Dockerfile
  README.md
  cmd/controller/main.go
  controller-job.yaml
  go.mod
  go.sum
  pkg/client/client.go
  pkg/controller/controller_test.go
  service-account/role.yaml
  service-account/serviceaccount.yaml
  test-controller-job.yaml
  tests/fixture.go
  tests/mockclient.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#6 Remove unit testing for WatchConfig.
  go.sum
  pkg/client/client.go
  pkg/config/secret-sync-config_test.go
  test-agent-job.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#10 Remove github action
  .github/workflows/test.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7 Add files from template-project
  CONTRIBUTING.md
  SECURITY_CONTACTS
  code-of-conduct.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8 Add support for building/pushing images via GCB
  Makefile
  README.md
  cmd/secret-sync-controller/main.go
  images/build.sh
  images/cloudbuild.yaml
  images/default/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/L

#12 Modify project layout.
  README.md
  cmd/demo/demo-job.yaml
  cmd/demo/demo.go
  cmd/secret-sync-controller/main.go
  controller-job.yaml
  go.mod
  secret-sync-controller/client/client.go
  secret-sync-controller/config/agent.go
  secret-sync-controller/config/secret-sync-config.go
  secret-sync-controller/config/secret-sync-config_test.go
  secret-sync-controller/controller/controller.go
  secret-sync-controller/controller/controller_test.go
  test-controller-job.yaml
  tests/fixture.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#15 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#16 Fix build failure in Makefile
  Makefile
  cmd/demo/demo.go
  go.mod
  images/default/Dockerfile
  secret-sync-controller/controller/controller_test.go
  secret-sync-controller/tests/fixture.go
  secret-sync-controller/tests/mockclient.go
Labels: approved, cncf-cla: yes, lgtm, size/S
